[Interface]
Address = 10.88.0.1/24
ListenPort = __WG_PORT__
PrivateKey = __WG_PRIVATE_KEY__
PostUp   = iptables -t nat -A POSTROUTING -s 10.88.0.0/24 -o %i -j MASQUERADE; iptables -A FORWARD -i %i -j ACCEPT; iptables -A FORWARD -o %i -j ACCEPT
PostDown = iptables -t nat -D POSTROUTING -s 10.88.0.0/24 -o %i -j MASQUERADE; iptables -D FORWARD -i %i -j ACCEPT; iptables -D FORWARD -o %i -j ACCEPT

# Peer (entry-нода) — добавляется автоматически:
# [Peer]
# PublicKey = <ENTRY_PUB>
# PresharedKey = __WG_PSK__
# AllowedIPs = 10.88.0.2/32
